# CMake generated Testfile for 
# Source directory: C:/Users/lwnkuh2/Desktop/Trials/CMake-Trial
# Build directory: C:/Users/lwnkuh2/Desktop/Trials/CMake-Trial
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(Runs "C:/Users/lwnkuh2/Desktop/Trials/CMake-Trial/Debug/Tutorial.exe" "25")
  set_tests_properties(Runs PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/lwnkuh2/Desktop/Trials/CMake-Trial/CMakeLists.txt;61;add_test;C:/Users/lwnkuh2/Desktop/Trials/CMake-Trial/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(Runs "C:/Users/lwnkuh2/Desktop/Trials/CMake-Trial/Release/Tutorial.exe" "25")
  set_tests_properties(Runs PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/lwnkuh2/Desktop/Trials/CMake-Trial/CMakeLists.txt;61;add_test;C:/Users/lwnkuh2/Desktop/Trials/CMake-Trial/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(Runs "C:/Users/lwnkuh2/Desktop/Trials/CMake-Trial/MinSizeRel/Tutorial.exe" "25")
  set_tests_properties(Runs PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/lwnkuh2/Desktop/Trials/CMake-Trial/CMakeLists.txt;61;add_test;C:/Users/lwnkuh2/Desktop/Trials/CMake-Trial/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(Runs "C:/Users/lwnkuh2/Desktop/Trials/CMake-Trial/RelWithDebInfo/Tutorial.exe" "25")
  set_tests_properties(Runs PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/lwnkuh2/Desktop/Trials/CMake-Trial/CMakeLists.txt;61;add_test;C:/Users/lwnkuh2/Desktop/Trials/CMake-Trial/CMakeLists.txt;0;")
else()
  add_test(Runs NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(Usage "C:/Users/lwnkuh2/Desktop/Trials/CMake-Trial/Debug/Tutorial.exe")
  set_tests_properties(Usage PROPERTIES  PASS_REGULAR_EXPRESSION "Usage:.*number" _BACKTRACE_TRIPLES "C:/Users/lwnkuh2/Desktop/Trials/CMake-Trial/CMakeLists.txt;64;add_test;C:/Users/lwnkuh2/Desktop/Trials/CMake-Trial/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(Usage "C:/Users/lwnkuh2/Desktop/Trials/CMake-Trial/Release/Tutorial.exe")
  set_tests_properties(Usage PROPERTIES  PASS_REGULAR_EXPRESSION "Usage:.*number" _BACKTRACE_TRIPLES "C:/Users/lwnkuh2/Desktop/Trials/CMake-Trial/CMakeLists.txt;64;add_test;C:/Users/lwnkuh2/Desktop/Trials/CMake-Trial/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(Usage "C:/Users/lwnkuh2/Desktop/Trials/CMake-Trial/MinSizeRel/Tutorial.exe")
  set_tests_properties(Usage PROPERTIES  PASS_REGULAR_EXPRESSION "Usage:.*number" _BACKTRACE_TRIPLES "C:/Users/lwnkuh2/Desktop/Trials/CMake-Trial/CMakeLists.txt;64;add_test;C:/Users/lwnkuh2/Desktop/Trials/CMake-Trial/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(Usage "C:/Users/lwnkuh2/Desktop/Trials/CMake-Trial/RelWithDebInfo/Tutorial.exe")
  set_tests_properties(Usage PROPERTIES  PASS_REGULAR_EXPRESSION "Usage:.*number" _BACKTRACE_TRIPLES "C:/Users/lwnkuh2/Desktop/Trials/CMake-Trial/CMakeLists.txt;64;add_test;C:/Users/lwnkuh2/Desktop/Trials/CMake-Trial/CMakeLists.txt;0;")
else()
  add_test(Usage NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(StandardUse "C:/Users/lwnkuh2/Desktop/Trials/CMake-Trial/Debug/Tutorial.exe" "4")
  set_tests_properties(StandardUse PROPERTIES  PASS_REGULAR_EXPRESSION "4 is 2" _BACKTRACE_TRIPLES "C:/Users/lwnkuh2/Desktop/Trials/CMake-Trial/CMakeLists.txt;68;add_test;C:/Users/lwnkuh2/Desktop/Trials/CMake-Trial/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(StandardUse "C:/Users/lwnkuh2/Desktop/Trials/CMake-Trial/Release/Tutorial.exe" "4")
  set_tests_properties(StandardUse PROPERTIES  PASS_REGULAR_EXPRESSION "4 is 2" _BACKTRACE_TRIPLES "C:/Users/lwnkuh2/Desktop/Trials/CMake-Trial/CMakeLists.txt;68;add_test;C:/Users/lwnkuh2/Desktop/Trials/CMake-Trial/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(StandardUse "C:/Users/lwnkuh2/Desktop/Trials/CMake-Trial/MinSizeRel/Tutorial.exe" "4")
  set_tests_properties(StandardUse PROPERTIES  PASS_REGULAR_EXPRESSION "4 is 2" _BACKTRACE_TRIPLES "C:/Users/lwnkuh2/Desktop/Trials/CMake-Trial/CMakeLists.txt;68;add_test;C:/Users/lwnkuh2/Desktop/Trials/CMake-Trial/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(StandardUse "C:/Users/lwnkuh2/Desktop/Trials/CMake-Trial/RelWithDebInfo/Tutorial.exe" "4")
  set_tests_properties(StandardUse PROPERTIES  PASS_REGULAR_EXPRESSION "4 is 2" _BACKTRACE_TRIPLES "C:/Users/lwnkuh2/Desktop/Trials/CMake-Trial/CMakeLists.txt;68;add_test;C:/Users/lwnkuh2/Desktop/Trials/CMake-Trial/CMakeLists.txt;0;")
else()
  add_test(StandardUse NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(Comp4 "C:/Users/lwnkuh2/Desktop/Trials/CMake-Trial/Debug/Tutorial.exe" "4")
  set_tests_properties(Comp4 PROPERTIES  PASS_REGULAR_EXPRESSION "4 is 2" _BACKTRACE_TRIPLES "C:/Users/lwnkuh2/Desktop/Trials/CMake-Trial/CMakeLists.txt;73;add_test;C:/Users/lwnkuh2/Desktop/Trials/CMake-Trial/CMakeLists.txt;80;do_test;C:/Users/lwnkuh2/Desktop/Trials/CMake-Trial/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(Comp4 "C:/Users/lwnkuh2/Desktop/Trials/CMake-Trial/Release/Tutorial.exe" "4")
  set_tests_properties(Comp4 PROPERTIES  PASS_REGULAR_EXPRESSION "4 is 2" _BACKTRACE_TRIPLES "C:/Users/lwnkuh2/Desktop/Trials/CMake-Trial/CMakeLists.txt;73;add_test;C:/Users/lwnkuh2/Desktop/Trials/CMake-Trial/CMakeLists.txt;80;do_test;C:/Users/lwnkuh2/Desktop/Trials/CMake-Trial/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(Comp4 "C:/Users/lwnkuh2/Desktop/Trials/CMake-Trial/MinSizeRel/Tutorial.exe" "4")
  set_tests_properties(Comp4 PROPERTIES  PASS_REGULAR_EXPRESSION "4 is 2" _BACKTRACE_TRIPLES "C:/Users/lwnkuh2/Desktop/Trials/CMake-Trial/CMakeLists.txt;73;add_test;C:/Users/lwnkuh2/Desktop/Trials/CMake-Trial/CMakeLists.txt;80;do_test;C:/Users/lwnkuh2/Desktop/Trials/CMake-Trial/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(Comp4 "C:/Users/lwnkuh2/Desktop/Trials/CMake-Trial/RelWithDebInfo/Tutorial.exe" "4")
  set_tests_properties(Comp4 PROPERTIES  PASS_REGULAR_EXPRESSION "4 is 2" _BACKTRACE_TRIPLES "C:/Users/lwnkuh2/Desktop/Trials/CMake-Trial/CMakeLists.txt;73;add_test;C:/Users/lwnkuh2/Desktop/Trials/CMake-Trial/CMakeLists.txt;80;do_test;C:/Users/lwnkuh2/Desktop/Trials/CMake-Trial/CMakeLists.txt;0;")
else()
  add_test(Comp4 NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(Comp9 "C:/Users/lwnkuh2/Desktop/Trials/CMake-Trial/Debug/Tutorial.exe" "9")
  set_tests_properties(Comp9 PROPERTIES  PASS_REGULAR_EXPRESSION "9 is 3" _BACKTRACE_TRIPLES "C:/Users/lwnkuh2/Desktop/Trials/CMake-Trial/CMakeLists.txt;73;add_test;C:/Users/lwnkuh2/Desktop/Trials/CMake-Trial/CMakeLists.txt;81;do_test;C:/Users/lwnkuh2/Desktop/Trials/CMake-Trial/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(Comp9 "C:/Users/lwnkuh2/Desktop/Trials/CMake-Trial/Release/Tutorial.exe" "9")
  set_tests_properties(Comp9 PROPERTIES  PASS_REGULAR_EXPRESSION "9 is 3" _BACKTRACE_TRIPLES "C:/Users/lwnkuh2/Desktop/Trials/CMake-Trial/CMakeLists.txt;73;add_test;C:/Users/lwnkuh2/Desktop/Trials/CMake-Trial/CMakeLists.txt;81;do_test;C:/Users/lwnkuh2/Desktop/Trials/CMake-Trial/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(Comp9 "C:/Users/lwnkuh2/Desktop/Trials/CMake-Trial/MinSizeRel/Tutorial.exe" "9")
  set_tests_properties(Comp9 PROPERTIES  PASS_REGULAR_EXPRESSION "9 is 3" _BACKTRACE_TRIPLES "C:/Users/lwnkuh2/Desktop/Trials/CMake-Trial/CMakeLists.txt;73;add_test;C:/Users/lwnkuh2/Desktop/Trials/CMake-Trial/CMakeLists.txt;81;do_test;C:/Users/lwnkuh2/Desktop/Trials/CMake-Trial/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(Comp9 "C:/Users/lwnkuh2/Desktop/Trials/CMake-Trial/RelWithDebInfo/Tutorial.exe" "9")
  set_tests_properties(Comp9 PROPERTIES  PASS_REGULAR_EXPRESSION "9 is 3" _BACKTRACE_TRIPLES "C:/Users/lwnkuh2/Desktop/Trials/CMake-Trial/CMakeLists.txt;73;add_test;C:/Users/lwnkuh2/Desktop/Trials/CMake-Trial/CMakeLists.txt;81;do_test;C:/Users/lwnkuh2/Desktop/Trials/CMake-Trial/CMakeLists.txt;0;")
else()
  add_test(Comp9 NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(Comp5 "C:/Users/lwnkuh2/Desktop/Trials/CMake-Trial/Debug/Tutorial.exe" "5")
  set_tests_properties(Comp5 PROPERTIES  PASS_REGULAR_EXPRESSION "5 is 2.236" _BACKTRACE_TRIPLES "C:/Users/lwnkuh2/Desktop/Trials/CMake-Trial/CMakeLists.txt;73;add_test;C:/Users/lwnkuh2/Desktop/Trials/CMake-Trial/CMakeLists.txt;82;do_test;C:/Users/lwnkuh2/Desktop/Trials/CMake-Trial/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(Comp5 "C:/Users/lwnkuh2/Desktop/Trials/CMake-Trial/Release/Tutorial.exe" "5")
  set_tests_properties(Comp5 PROPERTIES  PASS_REGULAR_EXPRESSION "5 is 2.236" _BACKTRACE_TRIPLES "C:/Users/lwnkuh2/Desktop/Trials/CMake-Trial/CMakeLists.txt;73;add_test;C:/Users/lwnkuh2/Desktop/Trials/CMake-Trial/CMakeLists.txt;82;do_test;C:/Users/lwnkuh2/Desktop/Trials/CMake-Trial/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(Comp5 "C:/Users/lwnkuh2/Desktop/Trials/CMake-Trial/MinSizeRel/Tutorial.exe" "5")
  set_tests_properties(Comp5 PROPERTIES  PASS_REGULAR_EXPRESSION "5 is 2.236" _BACKTRACE_TRIPLES "C:/Users/lwnkuh2/Desktop/Trials/CMake-Trial/CMakeLists.txt;73;add_test;C:/Users/lwnkuh2/Desktop/Trials/CMake-Trial/CMakeLists.txt;82;do_test;C:/Users/lwnkuh2/Desktop/Trials/CMake-Trial/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(Comp5 "C:/Users/lwnkuh2/Desktop/Trials/CMake-Trial/RelWithDebInfo/Tutorial.exe" "5")
  set_tests_properties(Comp5 PROPERTIES  PASS_REGULAR_EXPRESSION "5 is 2.236" _BACKTRACE_TRIPLES "C:/Users/lwnkuh2/Desktop/Trials/CMake-Trial/CMakeLists.txt;73;add_test;C:/Users/lwnkuh2/Desktop/Trials/CMake-Trial/CMakeLists.txt;82;do_test;C:/Users/lwnkuh2/Desktop/Trials/CMake-Trial/CMakeLists.txt;0;")
else()
  add_test(Comp5 NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(Comp7 "C:/Users/lwnkuh2/Desktop/Trials/CMake-Trial/Debug/Tutorial.exe" "7")
  set_tests_properties(Comp7 PROPERTIES  PASS_REGULAR_EXPRESSION "7 is 2.645" _BACKTRACE_TRIPLES "C:/Users/lwnkuh2/Desktop/Trials/CMake-Trial/CMakeLists.txt;73;add_test;C:/Users/lwnkuh2/Desktop/Trials/CMake-Trial/CMakeLists.txt;83;do_test;C:/Users/lwnkuh2/Desktop/Trials/CMake-Trial/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(Comp7 "C:/Users/lwnkuh2/Desktop/Trials/CMake-Trial/Release/Tutorial.exe" "7")
  set_tests_properties(Comp7 PROPERTIES  PASS_REGULAR_EXPRESSION "7 is 2.645" _BACKTRACE_TRIPLES "C:/Users/lwnkuh2/Desktop/Trials/CMake-Trial/CMakeLists.txt;73;add_test;C:/Users/lwnkuh2/Desktop/Trials/CMake-Trial/CMakeLists.txt;83;do_test;C:/Users/lwnkuh2/Desktop/Trials/CMake-Trial/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(Comp7 "C:/Users/lwnkuh2/Desktop/Trials/CMake-Trial/MinSizeRel/Tutorial.exe" "7")
  set_tests_properties(Comp7 PROPERTIES  PASS_REGULAR_EXPRESSION "7 is 2.645" _BACKTRACE_TRIPLES "C:/Users/lwnkuh2/Desktop/Trials/CMake-Trial/CMakeLists.txt;73;add_test;C:/Users/lwnkuh2/Desktop/Trials/CMake-Trial/CMakeLists.txt;83;do_test;C:/Users/lwnkuh2/Desktop/Trials/CMake-Trial/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(Comp7 "C:/Users/lwnkuh2/Desktop/Trials/CMake-Trial/RelWithDebInfo/Tutorial.exe" "7")
  set_tests_properties(Comp7 PROPERTIES  PASS_REGULAR_EXPRESSION "7 is 2.645" _BACKTRACE_TRIPLES "C:/Users/lwnkuh2/Desktop/Trials/CMake-Trial/CMakeLists.txt;73;add_test;C:/Users/lwnkuh2/Desktop/Trials/CMake-Trial/CMakeLists.txt;83;do_test;C:/Users/lwnkuh2/Desktop/Trials/CMake-Trial/CMakeLists.txt;0;")
else()
  add_test(Comp7 NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(Comp25 "C:/Users/lwnkuh2/Desktop/Trials/CMake-Trial/Debug/Tutorial.exe" "25")
  set_tests_properties(Comp25 PROPERTIES  PASS_REGULAR_EXPRESSION "25 is 5" _BACKTRACE_TRIPLES "C:/Users/lwnkuh2/Desktop/Trials/CMake-Trial/CMakeLists.txt;73;add_test;C:/Users/lwnkuh2/Desktop/Trials/CMake-Trial/CMakeLists.txt;84;do_test;C:/Users/lwnkuh2/Desktop/Trials/CMake-Trial/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(Comp25 "C:/Users/lwnkuh2/Desktop/Trials/CMake-Trial/Release/Tutorial.exe" "25")
  set_tests_properties(Comp25 PROPERTIES  PASS_REGULAR_EXPRESSION "25 is 5" _BACKTRACE_TRIPLES "C:/Users/lwnkuh2/Desktop/Trials/CMake-Trial/CMakeLists.txt;73;add_test;C:/Users/lwnkuh2/Desktop/Trials/CMake-Trial/CMakeLists.txt;84;do_test;C:/Users/lwnkuh2/Desktop/Trials/CMake-Trial/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(Comp25 "C:/Users/lwnkuh2/Desktop/Trials/CMake-Trial/MinSizeRel/Tutorial.exe" "25")
  set_tests_properties(Comp25 PROPERTIES  PASS_REGULAR_EXPRESSION "25 is 5" _BACKTRACE_TRIPLES "C:/Users/lwnkuh2/Desktop/Trials/CMake-Trial/CMakeLists.txt;73;add_test;C:/Users/lwnkuh2/Desktop/Trials/CMake-Trial/CMakeLists.txt;84;do_test;C:/Users/lwnkuh2/Desktop/Trials/CMake-Trial/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(Comp25 "C:/Users/lwnkuh2/Desktop/Trials/CMake-Trial/RelWithDebInfo/Tutorial.exe" "25")
  set_tests_properties(Comp25 PROPERTIES  PASS_REGULAR_EXPRESSION "25 is 5" _BACKTRACE_TRIPLES "C:/Users/lwnkuh2/Desktop/Trials/CMake-Trial/CMakeLists.txt;73;add_test;C:/Users/lwnkuh2/Desktop/Trials/CMake-Trial/CMakeLists.txt;84;do_test;C:/Users/lwnkuh2/Desktop/Trials/CMake-Trial/CMakeLists.txt;0;")
else()
  add_test(Comp25 NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(Comp-25 "C:/Users/lwnkuh2/Desktop/Trials/CMake-Trial/Debug/Tutorial.exe" "-25")
  set_tests_properties(Comp-25 PROPERTIES  PASS_REGULAR_EXPRESSION "-25 is (-nan|nan|0)" _BACKTRACE_TRIPLES "C:/Users/lwnkuh2/Desktop/Trials/CMake-Trial/CMakeLists.txt;73;add_test;C:/Users/lwnkuh2/Desktop/Trials/CMake-Trial/CMakeLists.txt;85;do_test;C:/Users/lwnkuh2/Desktop/Trials/CMake-Trial/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(Comp-25 "C:/Users/lwnkuh2/Desktop/Trials/CMake-Trial/Release/Tutorial.exe" "-25")
  set_tests_properties(Comp-25 PROPERTIES  PASS_REGULAR_EXPRESSION "-25 is (-nan|nan|0)" _BACKTRACE_TRIPLES "C:/Users/lwnkuh2/Desktop/Trials/CMake-Trial/CMakeLists.txt;73;add_test;C:/Users/lwnkuh2/Desktop/Trials/CMake-Trial/CMakeLists.txt;85;do_test;C:/Users/lwnkuh2/Desktop/Trials/CMake-Trial/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(Comp-25 "C:/Users/lwnkuh2/Desktop/Trials/CMake-Trial/MinSizeRel/Tutorial.exe" "-25")
  set_tests_properties(Comp-25 PROPERTIES  PASS_REGULAR_EXPRESSION "-25 is (-nan|nan|0)" _BACKTRACE_TRIPLES "C:/Users/lwnkuh2/Desktop/Trials/CMake-Trial/CMakeLists.txt;73;add_test;C:/Users/lwnkuh2/Desktop/Trials/CMake-Trial/CMakeLists.txt;85;do_test;C:/Users/lwnkuh2/Desktop/Trials/CMake-Trial/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(Comp-25 "C:/Users/lwnkuh2/Desktop/Trials/CMake-Trial/RelWithDebInfo/Tutorial.exe" "-25")
  set_tests_properties(Comp-25 PROPERTIES  PASS_REGULAR_EXPRESSION "-25 is (-nan|nan|0)" _BACKTRACE_TRIPLES "C:/Users/lwnkuh2/Desktop/Trials/CMake-Trial/CMakeLists.txt;73;add_test;C:/Users/lwnkuh2/Desktop/Trials/CMake-Trial/CMakeLists.txt;85;do_test;C:/Users/lwnkuh2/Desktop/Trials/CMake-Trial/CMakeLists.txt;0;")
else()
  add_test(Comp-25 NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(Comp0.0001 "C:/Users/lwnkuh2/Desktop/Trials/CMake-Trial/Debug/Tutorial.exe" "0.0001")
  set_tests_properties(Comp0.0001 PROPERTIES  PASS_REGULAR_EXPRESSION "0.0001 is 0.01" _BACKTRACE_TRIPLES "C:/Users/lwnkuh2/Desktop/Trials/CMake-Trial/CMakeLists.txt;73;add_test;C:/Users/lwnkuh2/Desktop/Trials/CMake-Trial/CMakeLists.txt;86;do_test;C:/Users/lwnkuh2/Desktop/Trials/CMake-Trial/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(Comp0.0001 "C:/Users/lwnkuh2/Desktop/Trials/CMake-Trial/Release/Tutorial.exe" "0.0001")
  set_tests_properties(Comp0.0001 PROPERTIES  PASS_REGULAR_EXPRESSION "0.0001 is 0.01" _BACKTRACE_TRIPLES "C:/Users/lwnkuh2/Desktop/Trials/CMake-Trial/CMakeLists.txt;73;add_test;C:/Users/lwnkuh2/Desktop/Trials/CMake-Trial/CMakeLists.txt;86;do_test;C:/Users/lwnkuh2/Desktop/Trials/CMake-Trial/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(Comp0.0001 "C:/Users/lwnkuh2/Desktop/Trials/CMake-Trial/MinSizeRel/Tutorial.exe" "0.0001")
  set_tests_properties(Comp0.0001 PROPERTIES  PASS_REGULAR_EXPRESSION "0.0001 is 0.01" _BACKTRACE_TRIPLES "C:/Users/lwnkuh2/Desktop/Trials/CMake-Trial/CMakeLists.txt;73;add_test;C:/Users/lwnkuh2/Desktop/Trials/CMake-Trial/CMakeLists.txt;86;do_test;C:/Users/lwnkuh2/Desktop/Trials/CMake-Trial/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(Comp0.0001 "C:/Users/lwnkuh2/Desktop/Trials/CMake-Trial/RelWithDebInfo/Tutorial.exe" "0.0001")
  set_tests_properties(Comp0.0001 PROPERTIES  PASS_REGULAR_EXPRESSION "0.0001 is 0.01" _BACKTRACE_TRIPLES "C:/Users/lwnkuh2/Desktop/Trials/CMake-Trial/CMakeLists.txt;73;add_test;C:/Users/lwnkuh2/Desktop/Trials/CMake-Trial/CMakeLists.txt;86;do_test;C:/Users/lwnkuh2/Desktop/Trials/CMake-Trial/CMakeLists.txt;0;")
else()
  add_test(Comp0.0001 NOT_AVAILABLE)
endif()
subdirs("MathFunctions")
